[Server]
port = 5800
serverName = "xxx.xxxx.com"

# Certs.serverDir
[Certs]
# TLS证书
serverDir = "certs/"

[Mysql]
# host = "mysql:3306"
user = "root"
password = "XXXXX"
dbname="XXX"
# 是否打印日志
info = true

[Redis]
# redis url like : url="localhost:6379"
# url="redis:6379"
password = "xxxxx"
# Whether to clear the redis cache: true is yes, false is no
clearUp = true
# Maximum number of idle connections in the pool.
# maxIdle = 30
# 数据库编号
index = 1

[Emails]
# 发送邮件的名称 可以为空（此时则为邮箱名称）
sender = "XXXXX"
# 发送邮箱地址
fromemails = "xxxxx@xxx.com"
# 邮箱密码
password = "xxxxxxxxxxxx"
# 邮箱服务器地址
serverhost = "xxxxxxxxxxxxxxxxxx"
# 邮箱服务器端口
Serverport =587

